### ISSUE TITLE
limiting facet results?

### ISSUE THREAD

**Issue by ghost** [tokee/solr-cdx#2]
When using a query of type 16 a) (list of arc-files containing url) eg:

http://localhost...?q=sdomain:ar,com,adsclasificados,*&rows=0&facet=true&facet.field=arc&facet.limit=-1

How do I limit the results to only those arcs with more than zero urls matching the query (I have around a million arcs, so really don't want to list them all each time). 

I realise this is a Solr query, not a solr-cdx one, but not used to Solr and haven't found the answer so far.

**Comment by tokee** [comment]
`facet.mincount=1` should do the trick. More options at https://wiki.apache.org/solr/SimpleFacetParameters.

**Comment by ghost** [comment]
Perfect. Thanks. Seems the wiki may be a better starting point than the plethora of official docs.
